name: twinkle
description: "A flutter chat app with firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  get:
  flutter_screenutil:
  firebase_core:
  firebase_crashlytics:
  firebase_messaging:
  firebase_auth:
  google_sign_in:
  google_fonts:
  qr_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:

  uses-material-design: true
